<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-K66FFMU" failures="2" tests="24" name="com.demowebshopproject.tests.LoginTest" time="41.715" errors="1" timestamp="2024-12-16T15:35:20 IST" skipped="4">
  <testcase classname="com.demowebshopproject.tests.LoginTest" name="login" time="3.187"/>
  <testcase classname="com.demowebshopproject.tests.LoginTest" name="login" time="3.380"/>
  <testcase classname="com.demowebshopproject.tests.LoginTest" name="readAndDisplayMenuItems" time="0.373"/>
  <testcase classname="com.demowebshopproject.tests.LoginTest" name="readAndDisplayMenuItems" time="0.430"/>
  <testcase classname="com.demowebshopproject.tests.LoginTest" name="compareScreenshots" time="2.957"/>
  <testcase classname="com.demowebshopproject.tests.LoginTest" name="compareScreenshots" time="2.452"/>
  <testcase classname="com.demowebshopproject.tests.LoginTest" name="selectProductAndConfiguration" time="4.532"/>
  <testcase classname="com.demowebshopproject.tests.LoginTest" name="selectProductAndConfiguration" time="4.498"/>
  <testcase classname="com.demowebshopproject.tests.LoginTest" name="addProductToCart" time="1.068"/>
  <testcase classname="com.demowebshopproject.tests.LoginTest" name="addProductToCart" time="1.622"/>
  <testcase classname="com.demowebshopproject.tests.LoginTest" name="navigateToCartAndCheckout" time="3.521"/>
  <testcase classname="com.demowebshopproject.tests.LoginTest" name="navigateToCartAndCheckout" time="3.544"/>
  <testcase classname="com.demowebshopproject.tests.LoginTest" name="provideShippingAddressAndMethod" time="1.637"/>
  <testcase classname="com.demowebshopproject.tests.LoginTest" name="provideShippingAddressAndMethod" time="1.587"/>
  <testcase classname="com.demowebshopproject.tests.LoginTest" name="providePaymentMethodAndInfo" time="1.184"/>
  <testcase classname="com.demowebshopproject.tests.LoginTest" name="providePaymentMethodAndInfo" time="1.080"/>
  <testcase classname="com.demowebshopproject.tests.LoginTest" name="confirmOrderAndVeirfyOrderDetails" time="1.275">
    <error message="ScreenCapture path must not be null or empty" type="java.lang.IllegalArgumentException">
      <![CDATA[java.lang.IllegalArgumentException: ScreenCapture path must not be null or empty
at com.aventstack.extentreports.util.Assert.notEmpty(Assert.java:12)
at com.aventstack.extentreports.ExtentTest.addScreenCaptureFromPath(ExtentTest.java:1100)
at com.demowebshopproject.utils.ExtentReportManager.onTestFailure(ExtentReportManager.java:70)
at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:115)
at org.testng.internal.invokers.TestInvoker.runTestResultListener(TestInvoker.java:285)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:774)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </error>
  </testcase> <!-- confirmOrderAndVeirfyOrderDetails -->
  <testcase classname="com.demowebshopproject.tests.LoginTest" name="confirmOrderAndVeirfyOrderDetails" time="3.363"/>
  <testcase classname="com.demowebshopproject.tests.LoginTest" name="verifyTestFailure" time="0.019">
    <skipped/>
  </testcase> <!-- verifyTestFailure -->
  <testcase classname="com.demowebshopproject.tests.LoginTest" name="verifyTestFailure" time="0.003">
    <skipped/>
  </testcase> <!-- verifyTestFailure -->
  <testcase classname="com.demowebshopproject.tests.LoginTest" name="verifyTestFailure" time="0.000">
    <skipped/>
  </testcase> <!-- verifyTestFailure -->
  <testcase classname="com.demowebshopproject.tests.LoginTest" name="verifyTestFailure" time="0.001">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1067)
at org.testng.Assert.assertEquals(Assert.java:1031)
at org.testng.Assert.assertEquals(Assert.java:1077)
at com.demowebshopproject.tests.LoginTest.verifyTestFailure(LoginTest.java:232)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- verifyTestFailure -->
  <testcase classname="com.demowebshopproject.tests.LoginTest" name="verifyTestFailure" time="0.002">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1067)
at org.testng.Assert.assertEquals(Assert.java:1031)
at org.testng.Assert.assertEquals(Assert.java:1077)
at com.demowebshopproject.tests.LoginTest.verifyTestFailure(LoginTest.java:232)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- verifyTestFailure -->
  <testcase classname="com.demowebshopproject.tests.LoginTest" name="verifyTestFailure" time="0.000">
    <skipped/>
  </testcase> <!-- verifyTestFailure -->
</testsuite> <!-- com.demowebshopproject.tests.LoginTest -->
