<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="4" ignored="4" total="28" passed="17" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-12-16T15:34:41 IST" name="Suite" finished-at="2024-12-16T15:35:20 IST" duration-ms="38542">
    <groups>
    </groups>
    <test started-at="2024-12-16T15:34:41 IST" name="chromeTest" finished-at="2024-12-16T15:35:17 IST" duration-ms="36294">
      <class name="com.demowebshopproject.tests.LoginTest">
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:com.demowebshopproject.tests.LoginTest@45c8d09f]" started-at="2024-12-16T15:34:42 IST" name="setUp" finished-at="2024-12-16T15:34:56 IST" duration-ms="13933" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@44e3760b]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="login()[pri:1, instance:com.demowebshopproject.tests.LoginTest@45c8d09f]" started-at="2024-12-16T15:34:56 IST" name="login" finished-at="2024-12-16T15:34:59 IST" duration-ms="3187" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="readAndDisplayMenuItems()[pri:2, instance:com.demowebshopproject.tests.LoginTest@45c8d09f]" started-at="2024-12-16T15:34:59 IST" name="readAndDisplayMenuItems" finished-at="2024-12-16T15:34:59 IST" duration-ms="373" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- readAndDisplayMenuItems -->
        <test-method signature="compareScreenshots()[pri:3, instance:com.demowebshopproject.tests.LoginTest@45c8d09f]" started-at="2024-12-16T15:34:59 IST" name="compareScreenshots" finished-at="2024-12-16T15:35:02 IST" duration-ms="2957" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- compareScreenshots -->
        <test-method signature="selectProductAndConfiguration()[pri:4, instance:com.demowebshopproject.tests.LoginTest@45c8d09f]" started-at="2024-12-16T15:35:02 IST" name="selectProductAndConfiguration" finished-at="2024-12-16T15:35:07 IST" duration-ms="4532" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectProductAndConfiguration -->
        <test-method signature="addProductToCart()[pri:5, instance:com.demowebshopproject.tests.LoginTest@45c8d09f]" started-at="2024-12-16T15:35:07 IST" name="addProductToCart" finished-at="2024-12-16T15:35:08 IST" duration-ms="1622" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addProductToCart -->
        <test-method signature="navigateToCartAndCheckout()[pri:6, instance:com.demowebshopproject.tests.LoginTest@45c8d09f]" started-at="2024-12-16T15:35:08 IST" name="navigateToCartAndCheckout" finished-at="2024-12-16T15:35:12 IST" duration-ms="3544" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigateToCartAndCheckout -->
        <test-method signature="provideShippingAddressAndMethod()[pri:7, instance:com.demowebshopproject.tests.LoginTest@45c8d09f]" started-at="2024-12-16T15:35:12 IST" name="provideShippingAddressAndMethod" finished-at="2024-12-16T15:35:13 IST" duration-ms="1587" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- provideShippingAddressAndMethod -->
        <test-method signature="providePaymentMethodAndInfo()[pri:8, instance:com.demowebshopproject.tests.LoginTest@45c8d09f]" started-at="2024-12-16T15:35:13 IST" name="providePaymentMethodAndInfo" finished-at="2024-12-16T15:35:15 IST" duration-ms="1184" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- providePaymentMethodAndInfo -->
        <test-method signature="confirmOrderAndVeirfyOrderDetails()[pri:9, instance:com.demowebshopproject.tests.LoginTest@45c8d09f]" started-at="2024-12-16T15:35:15 IST" name="confirmOrderAndVeirfyOrderDetails" finished-at="2024-12-16T15:35:16 IST" duration-ms="1275" status="FAIL">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[ScreenCapture path must not be null or empty]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: ScreenCapture path must not be null or empty
at com.aventstack.extentreports.util.Assert.notEmpty(Assert.java:12)
at com.aventstack.extentreports.ExtentTest.addScreenCaptureFromPath(ExtentTest.java:1100)
at com.demowebshopproject.utils.ExtentReportManager.onTestFailure(ExtentReportManager.java:70)
at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:115)
at org.testng.internal.invokers.TestInvoker.runTestResultListener(TestInvoker.java:285)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:774)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- confirmOrderAndVeirfyOrderDetails -->
        <test-method retried="true" signature="verifyTestFailure()[pri:10, instance:com.demowebshopproject.tests.LoginTest@45c8d09f]" started-at="2024-12-16T15:35:16 IST" name="verifyTestFailure" finished-at="2024-12-16T15:35:16 IST" duration-ms="19" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1067)
at org.testng.Assert.assertEquals(Assert.java:1031)
at org.testng.Assert.assertEquals(Assert.java:1077)
at com.demowebshopproject.tests.LoginTest.verifyTestFailure(LoginTest.java:232)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyTestFailure -->
        <test-method retried="true" signature="verifyTestFailure()[pri:10, instance:com.demowebshopproject.tests.LoginTest@45c8d09f]" started-at="2024-12-16T15:35:16 IST" name="verifyTestFailure" finished-at="2024-12-16T15:35:16 IST" duration-ms="3" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1067)
at org.testng.Assert.assertEquals(Assert.java:1031)
at org.testng.Assert.assertEquals(Assert.java:1077)
at com.demowebshopproject.tests.LoginTest.verifyTestFailure(LoginTest.java:232)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyTestFailure -->
        <test-method signature="verifyTestFailure()[pri:10, instance:com.demowebshopproject.tests.LoginTest@45c8d09f]" started-at="2024-12-16T15:35:16 IST" name="verifyTestFailure" finished-at="2024-12-16T15:35:16 IST" duration-ms="2" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1067)
at org.testng.Assert.assertEquals(Assert.java:1031)
at org.testng.Assert.assertEquals(Assert.java:1077)
at com.demowebshopproject.tests.LoginTest.verifyTestFailure(LoginTest.java:232)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyTestFailure -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.demowebshopproject.tests.LoginTest@45c8d09f]" started-at="2024-12-16T15:35:17 IST" name="teardown" finished-at="2024-12-16T15:35:17 IST" duration-ms="832" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.demowebshopproject.tests.LoginTest -->
    </test> <!-- chromeTest -->
    <test started-at="2024-12-16T15:34:41 IST" name="edgeTest" finished-at="2024-12-16T15:35:20 IST" duration-ms="38542">
      <class name="com.demowebshopproject.tests.LoginTest">
        <test-method is-config="true" signature="setUp(java.lang.String,org.testng.ITestContext)[pri:0, instance:com.demowebshopproject.tests.LoginTest@3b220bcb]" started-at="2024-12-16T15:34:41 IST" name="setUp" finished-at="2024-12-16T15:34:56 IST" duration-ms="14555" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[edge]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@4e517165]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="login()[pri:1, instance:com.demowebshopproject.tests.LoginTest@3b220bcb]" started-at="2024-12-16T15:34:56 IST" name="login" finished-at="2024-12-16T15:34:59 IST" duration-ms="3380" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="readAndDisplayMenuItems()[pri:2, instance:com.demowebshopproject.tests.LoginTest@3b220bcb]" started-at="2024-12-16T15:34:59 IST" name="readAndDisplayMenuItems" finished-at="2024-12-16T15:35:00 IST" duration-ms="430" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- readAndDisplayMenuItems -->
        <test-method signature="compareScreenshots()[pri:3, instance:com.demowebshopproject.tests.LoginTest@3b220bcb]" started-at="2024-12-16T15:35:00 IST" name="compareScreenshots" finished-at="2024-12-16T15:35:02 IST" duration-ms="2452" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- compareScreenshots -->
        <test-method signature="selectProductAndConfiguration()[pri:4, instance:com.demowebshopproject.tests.LoginTest@3b220bcb]" started-at="2024-12-16T15:35:02 IST" name="selectProductAndConfiguration" finished-at="2024-12-16T15:35:07 IST" duration-ms="4498" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectProductAndConfiguration -->
        <test-method signature="addProductToCart()[pri:5, instance:com.demowebshopproject.tests.LoginTest@3b220bcb]" started-at="2024-12-16T15:35:07 IST" name="addProductToCart" finished-at="2024-12-16T15:35:08 IST" duration-ms="1068" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addProductToCart -->
        <test-method signature="navigateToCartAndCheckout()[pri:6, instance:com.demowebshopproject.tests.LoginTest@3b220bcb]" started-at="2024-12-16T15:35:08 IST" name="navigateToCartAndCheckout" finished-at="2024-12-16T15:35:11 IST" duration-ms="3521" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigateToCartAndCheckout -->
        <test-method signature="provideShippingAddressAndMethod()[pri:7, instance:com.demowebshopproject.tests.LoginTest@3b220bcb]" started-at="2024-12-16T15:35:11 IST" name="provideShippingAddressAndMethod" finished-at="2024-12-16T15:35:13 IST" duration-ms="1637" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- provideShippingAddressAndMethod -->
        <test-method signature="providePaymentMethodAndInfo()[pri:8, instance:com.demowebshopproject.tests.LoginTest@3b220bcb]" started-at="2024-12-16T15:35:13 IST" name="providePaymentMethodAndInfo" finished-at="2024-12-16T15:35:14 IST" duration-ms="1080" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- providePaymentMethodAndInfo -->
        <test-method signature="confirmOrderAndVeirfyOrderDetails()[pri:9, instance:com.demowebshopproject.tests.LoginTest@3b220bcb]" started-at="2024-12-16T15:35:14 IST" name="confirmOrderAndVeirfyOrderDetails" finished-at="2024-12-16T15:35:17 IST" duration-ms="3363" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- confirmOrderAndVeirfyOrderDetails -->
        <test-method retried="true" signature="verifyTestFailure()[pri:10, instance:com.demowebshopproject.tests.LoginTest@3b220bcb]" started-at="2024-12-16T15:35:17 IST" name="verifyTestFailure" finished-at="2024-12-16T15:35:17 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1067)
at org.testng.Assert.assertEquals(Assert.java:1031)
at org.testng.Assert.assertEquals(Assert.java:1077)
at com.demowebshopproject.tests.LoginTest.verifyTestFailure(LoginTest.java:232)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyTestFailure -->
        <test-method retried="true" signature="verifyTestFailure()[pri:10, instance:com.demowebshopproject.tests.LoginTest@3b220bcb]" started-at="2024-12-16T15:35:18 IST" name="verifyTestFailure" finished-at="2024-12-16T15:35:18 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1067)
at org.testng.Assert.assertEquals(Assert.java:1031)
at org.testng.Assert.assertEquals(Assert.java:1077)
at com.demowebshopproject.tests.LoginTest.verifyTestFailure(LoginTest.java:232)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyTestFailure -->
        <test-method signature="verifyTestFailure()[pri:10, instance:com.demowebshopproject.tests.LoginTest@3b220bcb]" started-at="2024-12-16T15:35:18 IST" name="verifyTestFailure" finished-at="2024-12-16T15:35:18 IST" duration-ms="1" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1067)
at org.testng.Assert.assertEquals(Assert.java:1031)
at org.testng.Assert.assertEquals(Assert.java:1077)
at com.demowebshopproject.tests.LoginTest.verifyTestFailure(LoginTest.java:232)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyTestFailure -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.demowebshopproject.tests.LoginTest@3b220bcb]" started-at="2024-12-16T15:35:18 IST" name="teardown" finished-at="2024-12-16T15:35:20 IST" duration-ms="1838" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.demowebshopproject.tests.LoginTest -->
    </test> <!-- edgeTest -->
  </suite> <!-- Suite -->
</testng-results>
